# Redis Setup Script for Windows 11 (no Docker / Chocolatey required)
# Downloads the community Redis Windows build, installs as a Windows Service,
# and configures AOF persistence as required by the migration checkpoint design.
#
# Run once as Administrator:  .\setup-redis-windows.ps1
# To start manually later:    redis-server C:\Redis\redis.conf
# To stop the service:        Stop-Service redis

#Requires -RunAsAdministrator

$ErrorActionPreference = 'Stop'
$redisDir   = 'C:\Redis'
$redisPort  = 6379
$redisConf  = "$redisDir\redis.conf"
$redisExe   = "$redisDir\redis-server.exe"
$serviceName = 'redis'

# ---------- Step 1: Download Redis for Windows ----------
Write-Host "`n[1/5] Downloading Redis for Windows..." -ForegroundColor Cyan

# Community-maintained Windows builds of Redis 7.x:
#   https://github.com/redis-windows/redis-windows/releases
# Download the latest zip manually from the URL above and place the extracted
# folder at C:\Redis, then re-run this script from Step 2 onward if the
# automatic download below is blocked by your corporate proxy.

$zipUrl  = 'https://github.com/redis-windows/redis-windows/releases/download/7.4.2/Redis-7.4.2-Windows-x64-with-Service.zip'
$zipPath = "$env:TEMP\redis-windows.zip"

try {
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    Invoke-WebRequest -Uri $zipUrl -OutFile $zipPath -UseBasicParsing
    Write-Host "  Downloaded to $zipPath" -ForegroundColor Green
} catch {
    Write-Warning "Automatic download failed: $_"
    Write-Host @"

  MANUAL STEP REQUIRED
  --------------------
  1. Open a browser and go to:
       https://github.com/redis-windows/redis-windows/releases
  2. Download the latest  Redis-*-Windows-x64-with-Service.zip
  3. Extract its contents into  C:\Redis\
  4. Re-run this script.
"@
    exit 1
}

# ---------- Step 2: Extract ----------
Write-Host "`n[2/5] Extracting Redis..." -ForegroundColor Cyan

if (Test-Path $redisDir) {
    Write-Host "  $redisDir already exists — skipping extract (delete it first for a clean install)"
} else {
    Expand-Archive -Path $zipPath -DestinationPath $env:TEMP\redis-extract -Force
    # The zip may contain a versioned subfolder; find it
    $extracted = Get-ChildItem "$env:TEMP\redis-extract" -Directory | Select-Object -First 1
    if ($extracted) {
        Move-Item $extracted.FullName $redisDir
    } else {
        Move-Item "$env:TEMP\redis-extract" $redisDir
    }
}

if (-not (Test-Path $redisExe)) {
    Write-Error "redis-server.exe not found at $redisExe. Check the extracted folder structure."
}
Write-Host "  Redis binaries at $redisDir" -ForegroundColor Green

# ---------- Step 3: Write redis.conf ----------
Write-Host "`n[3/5] Writing redis.conf..." -ForegroundColor Cyan

$conf = @"
# LADWP Auth0 Migration — Redis configuration
# Generated by setup-redis-windows.ps1

bind 127.0.0.1
port $redisPort
protected-mode yes

# AOF persistence — required so checkpoint keys survive process restarts.
# Loss of Redis = loss of all migration checkpoint state.
appendonly yes
appendfsync everysec
appendfilename "appendonly.aof"

# Optional: set a password by uncommenting the line below.
# requirepass your_strong_password_here

# Log file
logfile "$redisDir\redis.log"

# Working directory (AOF + RDB files land here)
dir $redisDir

# Disable RDB snapshots — AOF alone is sufficient for this workload
save ""
"@

Set-Content -Path $redisConf -Value $conf -Encoding utf8
Write-Host "  Config written to $redisConf" -ForegroundColor Green

# ---------- Step 4: Install as Windows Service ----------
Write-Host "`n[4/5] Installing Redis as a Windows service..." -ForegroundColor Cyan

$existingService = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
if ($existingService) {
    Write-Host "  Service '$serviceName' already exists — skipping install"
} else {
    # redis-server supports --service-install natively
    & $redisExe --service-install $redisConf --service-name $serviceName
    Write-Host "  Service '$serviceName' installed" -ForegroundColor Green
}

# ---------- Step 5: Start the service ----------
Write-Host "`n[5/5] Starting Redis service..." -ForegroundColor Cyan
Start-Service -Name $serviceName
Start-Sleep -Seconds 2
$svc = Get-Service -Name $serviceName
Write-Host "  Service status: $($svc.Status)" -ForegroundColor $(if ($svc.Status -eq 'Running') { 'Green' } else { 'Red' })

# ---------- Verify ----------
Write-Host "`n--- Verification ---" -ForegroundColor Cyan
$redisCli = "$redisDir\redis-cli.exe"
if (Test-Path $redisCli) {
    $pong = & $redisCli -p $redisPort PING 2>$null
    if ($pong -eq 'PONG') {
        Write-Host "  redis-cli PING → PONG  (Redis is running)" -ForegroundColor Green
    } else {
        Write-Warning "  redis-cli did not respond — check $redisDir\redis.log"
    }
} else {
    Write-Host "  redis-cli not found; connect manually with: redis-cli -p $redisPort PING"
}

Write-Host @"

========================================================
  Redis is now running on 127.0.0.1:$redisPort
  Service name : $serviceName  (starts automatically on boot)
  Config file  : $redisConf
  Log file     : $redisDir\redis.log
  AOF data dir : $redisDir

  To load a test user into the migration source list:
    redis-cli RPUSH migration:source:users '{\"email\":\"test@ladwp.com\",\"uid\":\"test001\",\"first_name\":\"Test\",\"last_name\":\"User\",\"password_hash\":\"<base64hash>\",\"language_preference\":\"en\"}'

  To stop/start the service:
    Stop-Service  $serviceName
    Start-Service $serviceName
========================================================
"@ -ForegroundColor Cyan
